stable/locust: fix httpHeaders Authorization header value
deliveryhero/helm-charts pull request #272
Opened 2021-12-22 15:50 UTC by vtatarin

## Description

The current implementation of health check with Basic Auth is incorrect due to an error in the code below:
```
{{- if .Values.master.auth.enabled }}
            httpHeaders:
                - name: Authorization
                  value: Basic {{ cat .Values.master.auth.username ":" .Values.master.auth.password | b64enc }}
```
to be more precise, `cat .Values.master.auth.username ":" .Values.master.auth.password` generates a string "username : password" (see spaces) according to the [Helm documentation](https://helm.sh/docs/chart_template_guide/function_list/#cat).

This results in a pod being unable to start since the base64 encoded Authorization header is not what locust is expecting (it should be a string **without** spaces):
```
Events:
  Type     Reason     Age                   From               Message
  ----     ------     ----                  ----               -------
  Normal   Scheduled  4m55s                 default-scheduler  Successfully assigned locust/deliveryhero-locust-master-7755dbffb5-2kbss to cluster
  Normal   Pulled     4m54s                 kubelet            Container image "locustio/locust:2.4.0" already present on machine
  Normal   Created    4m54s                 kubelet            Created container locust
  Normal   Started    4m54s                 kubelet            Started container locust
  Warning  Unhealthy  19s (x10 over 4m49s)  kubelet            Readiness probe failed: HTTP probe failed with statuscode: 401
```

My proposal is to switch to a `printf` function which generates a string in a correct format: `username:password` (no spaces).

Thank you in advance!

## Checklist

- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)
- [x] I have read the [contribution instructions](https://github.com/deliveryhero/helm-charts#contributing), bumped chart version and regenerated the docs
- [ ] Github actions are passing

2022-01-03 09:22 UTC, max-rocket-internet requested changes
Can we remove the changes to `maintainers`? It's not that we don't want to acknowledge your very appreciated contribution, it's just that this chart has [many contributors](https://github.com/deliveryhero/helm-charts/commits/master/stable/locust) and if we start adding them all here it will just be a long list and continually updating list.

Personally I would remove the field but I think it's required.

I hope that's OK!

2022-01-03 09:22 UTC, max-rocket-internet commented on stable/locust/Chart.yaml
> +  email: bugaga1100@gmail.com
```suggestion
```

2022-01-03 09:22 UTC, max-rocket-internet commented on stable/locust/README.md
> +| Valerii Tatarin | bugaga1100@gmail.com |  |
```suggestion
```

2022-01-03 09:26 UTC, max-rocket-internet commented
CI also fails due to the maintainers change.

2022-01-12 13:55 UTC, vtatarin commented
Hey @max-rocket-internet 
Sure, merged your suggestion. Approve tests run, please

2022-01-13 11:12 UTC, max-rocket-internet approved these changes

2022-01-13 11:14 UTC, merged