[stable/backstage] Missing ingressClassName parameter
deliveryhero/helm-charts pull request #407
Opened 2022-11-20 23:47 UTC by brunowego

## Description

Currently, the parameter `ingressClassName` is missing.

## Checklist

- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)
- [x] I have read the [contribution instructions](https://github.com/deliveryhero/helm-charts#contributing), bumped chart version and regenerated the docs
- [ ] Github actions are passing

2022-11-21 09:18 UTC, max-rocket-internet requested changes
Thanks @brunowego but you need to bump the chart version and regenerate the README from the template 🙂

2022-11-21 12:53 UTC, max-rocket-internet commented
FYI I added clearer instructions here: https://github.com/deliveryhero/helm-charts#opening-a-pr

2022-12-03 15:37 UTC, brunowego commented
Sorry for the delay. Heavy week. :)

2022-12-05 09:56 UTC, max-rocket-internet approved these changes

2022-12-05 09:59 UTC, merged